config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'user/index' => 'user#index'
get 'photo/index/:id' => 'photo#index', as: 'user_photos'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.where(user_id: params[:id])
    @photo_i = Photo.all.where("user_id=?",params[:id])
    @comments_all = Comment.where(photo_id: @photo_i)
    @photo = Photo.find_by(id: @photo_i)
  end

  def show_user_name(user_id)
    @user = User.find_by(id: user_id)
    return  @user.first_name
  end
  helper_method :show_user_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users=User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<!Doctype html>
<html lang="en">
<body>
<h1>Photo Page</h1>

<br/>
<% @photo_i.each do |photo| %>
<%= image_tag("/assets/#{photo.file_name}") %>
<div class="cmt">
<p><strong>Photo posted on:</strong><%=photo.date_time %></p>

</div>
<% @comments_all.where("photo_id=?",photo.id).each do |comment| %>

  <div class="cmt">
    <p> <strong>Comment: </strong><%= comment.comment %></p>
    <p> <strong>Posted on: </strong><%= comment.created_at %></p>
    <p> <strong> Posted by : </strong> <%= link_to show_user_name(comment.user_id), user_photos_path(comment.user_id) %></p>


  </div>
<% end %>
<% end %>

</body>
</html>

app/views/user/index.html.erb
<!Doctype html>
<html lang="en">
<body>
<div>
 <h1>Photosite - ProjectR1</h1>
  <h2>List of Users</h2>
</div>
<table>
  <tr>
  <th>User Id</th>
  <th>First Name</th>
  <th>Last Name</th>
  </tr>

  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.id, user_photos_path(user.id) %></td>
    <td><%= link_to user.first_name, user_photos_path(user.id) %></td>
    <td><%= link_to user.last_name, user_photos_path(user.id) %></td>



  </tr>
 <%end%>

  </tbody>

</table>

</body>


</html>


